spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/cloud_vendor
    username: postgres
    password: 2049postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

